# AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'HelloSayer']

# Cell
def say_hello(name):
    """Say hello to somebody"""
    return f"Hello, {name}!"

# Cell
class HelloSayer:
    """Say hello to somebody"""

    def __init__(self, to):
        self.to = to

    def say(self):
        """Say hello"""
        return say_hello(self.to)